#encoding: utf-8
#saq定义的常量
#返现卡种类；
content_type:
  collections: [1,2,3,4,5,6]
  text: 1
  rich_text: 2
  geo: 3
  attachment: 4
  image: 5
  video: 6
applicant_type:
  all: [{name: 'vehicle',desc: '车证申请'},{name: 'resident',desc: '本地居民'},{name: 'foreigner',desc: '国外居民'}]
  all_fields: [{name: 'name', title: '姓名', type: 'String'},
  {name: 'en_name', title: '英文名称', type: 'String'},
  {name: 'birth', title: '出生日期', type: 'Date'},        {name: 'gender', title: '性别', type: 'String'},        {name: 'phone', title: '移动电话', type: 'String'},        {name: 'email', title: '邮件', type: 'String'},        {name: 'job_title', title: '职务', type: 'String'},        {name: 'country', title: '国家', type: 'String'},        {name: 'province', title: '省份', type: 'String'},        {name: 'city', title: '城市', type: 'String'},        {name: 'inhabit_address', title: '现居地址', type: 'String'},        {name: 'work_unit_abbr', title: '工作单位简称', type: 'String'},        {name: 'work_unit', title: '工作单位全称', type: 'String'},        {name: 'work_branch', title: '工作部门', type: 'String'},        {name: 'id_card', title: '身份证号', type: 'String'},        {name: 'id_card_expiry_date', title: '身份证号过期时间', type: 'String'},        {name: 'passport', title: '护照', type: 'String'},        {name: 'passport_expiry_date', title: '护照过期时间', type: 'String'},        {name: 'booth_no', title: '展位号', type: 'String'},        {name: 'vehicle_type', title: '车辆类型', type: 'String'},        {name: 'vehicle_no', title: '车牌号码', type: 'String'},        {name: 'type', title: '证卡类型', type: 'String'},        {name: 'photo', title: '照片', type: 'File'}       ]
  vehicle: [
    { name: 'vehicle_no', title: '车牌号码', type: 'String', desc: "车牌号格式：新A HZ123" },
    { name: 'name', title: '驾驶员姓名', type: 'String' },
    { name: 'id_card', title: '身份证号', type: 'String' },
    { name: 'phone', title: '联系方式(手机)', type: 'String' },
    { name: 'work_unit', title: '车辆所属单位', type: 'String' },
    { name: 'booth_no', title: '展位号', type: 'String' },
    { name: 'photo', title: '电子照片', type: 'File', desc: "上传要求:须近期免冠彩色白底JPG格式电子照片，照片横竖比例为3:4，文件大小20-30KB" } ]
  resident: [
    { name: 'name', title: '姓名', type: 'String' },
    { name: 'gender', title: '性别', type: 'String'},
    { name: 'id_card', title: '身份证号码', type: 'String', desc: "注意：身份证号码如有字母，请填写小写字母x"},
    { name: 'work_unit', title: '工作单位', type: 'String'},
    { name: 'job_title', title: '职务', type: 'String', rq: "false"},
    { name: 'province', title: '省份', type: 'String'},
    { name: 'city', title: '城市', type: 'String'},
    { name: 'inhabit_address', title: '现居地址', type: 'String'},
    { name: 'email', title: 'Email', type: 'String', rq: "false"},
    { name: 'phone', title: '手机号码', type: 'String'},
    { name: 'photo', title: '电子照片', type: 'File', desc: "上传要求:须近期免冠彩色白底JPG格式电子照片，照片横竖比例为3:4，文件大小20-30KB" } ]
  foreigner: [
    { name: 'name', title: '证件显示姓名', type: 'String'},
    { name: 'en_name', title: '英文姓名', type: 'String'},
    { name: 'birth', title: '出生年月日', type: 'Date'},
    { name: 'gender', title: '性别', type: 'String'},
    { name: 'id_type', title: '身份证类型', type: 'String'},
    { name: 'other_card', title: '证件号码', type: 'String'},
    { name: 'id_card_expiry_date', title: '身份证件有效期', type: 'Date'},
    { name: 'work_unit', title: '工作单位/服务机构', type: 'String'},
    { name: 'job_title', title: '职务', type: 'String', rq: "false"},
    { name: 'area', title: '国家地区', type: 'String'},
    { name: 'email', title: 'Email', type: 'String', rq: "false"},
    { name: 'phone', title: '手机号码', type: 'String' },
    { name: 'photo', title: '电子照片', type: 'File', desc: "上传要求:须近期免冠彩色白底JPG格式电子照片，照片横竖比例为3:4，文件大小20-30KB" } ]
card_type:
  professional_vistor_id: '558a23f0695a323e90010000'
