info_type:
  types:
    "信息类型": 0
    "后台配置": 1
    "相册类型": 2
exhibitor:
  scopes:
    - "消防"
    - "安防"
    - "警用"
    - "智能交通"
    - "智能家居"
    - "机器人"
    - "其他"
professional_visitor:
  sex:
    "男": 0
    "女": 1
  area:
    - "中国大陆"
    - "香港"
    - "澳门"
    - "台湾"
    - "其他国家及地区"
card:
  types:
    "jn_card": 0
    "jw_card": 1
    "cz_card": 2
  status:
    "审核未通过": -1
    "未提交": 0
    "已提交,等待审核": 1
    "审核通过,等待制卡": 2
    "制卡完成": 3
exhibitor:
  status:
    "审核未通过": -1
    "等待缴费审核": 0
    "缴费审核通过": 1
sms:
  time_out: 2
  accountSid: aaf98f894b827e71014b95b5954b03d6
  appId: aaf98f894b827e71014b95b64c7c03d8
  auth_token: a9b0aff4a9d143cf83195111961e5e99
  templateId: 1
  apiurl: https://sandboxapp.cloopen.com:8883
sms_templetes:
  professional_visitor_check_is_ok: 1
  professional_visitor_check_is_not_ok: 2
